jwt:
  header: Authorization
  secret:  ${JWT_SECRET}
  expiration: 86400
spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
      disableConnectionTracking: 'true'
      format_sql: 'true'
      show_sql: 'true'
      type: all
      use_sql_comments: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    protocol: smtps
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${BDD_USERNAME}
    username: ${BDD_PASSWORD}
    url: jdbc:postgresql://${BDD_URL}?useSSL=false
  servlet:
    multipart:
      enabled: 'true'
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2MB
mail:
  debug: 'false'
logging:
  level:
    fr:
      esgi:
        ecommerce:
          controller: debug
application:
  document:
    upload-directory: ${BACKEND_DIR_PATH}
  mail:
    sender: ${MAIL_SENDER}
hostname:  ${HOSTNAME}
server:
  port: ${PORT}
recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s
  secret: ${RECAPTCHA_SECRET}
